language: bash
services: docker
jobs:
  include:
    - stage: build
      script:
        - make all
        - docker images
    - stage: deploy
      provider: script
      script: docker push
      on:
        branch: master
env:
  matrix:
  - secure: KXqIr0Ah7H+cisHMBE9xyNdLmfjpiHZfiTpkaBsVcF2Hsntn5WZY3CMlw9c773muiym776vElyRgoE9SP7+qa9rVtJitXjlv7M5trJGoYVte9qjjCXdXa5QAc4/MlhNst1OhLMr64FYz9pfQRQ4OetY9dqe/zEXfqWZAG02s5TYaku9zAcX6NJLsYVuhYQqIPS3TsijnsarIOccioiwVMitGo55rmAKgKPRQ1m3v/JFKGgNpnvFnXg7gqFEupBEl0+armlvsbddDm3FBvoMxM+kFUGPnfF4KDZnqJ0oCdju4tPkpoTiERv9NeeLZqBcxVvYNpMNR7xb6t7XfwOCDJ6rQrlxXX7sS7QC4+GC7lJ8D4MoSJ5jMYbgOTv5jxoh52nRPofExosVL8qSB9YtM9oJJ21WkyCDfqvIJuwJ4pyAMx6uzZxJsCVguBmpoYPR5bs/eMIE2ME+AiPuM39PGBLtRO7JFLbtP9gEETk7Wvugk1POxTHIEVCiuHUH9bdsKAk8v0e6NynCrnBBLlBK1XSH81lRwiCfSqVpHxObLlUewXE86KGfaIqAr6z0oRPkpfysWMy7rK5L4WdjcuaOtM8Dgg4iI9Tnd/z4Be/krYIGpjzjYssWhHLj/QGXiLXx0iEjWPkHgbWyNoxuKWD4IlkNiWS1SdCVuOIGbJkbLjwY=
  - secure: IwHns7bp1sl2ZrFWWkXXHyOeerCa12aCqbci4O88tb2ektiYyn1cJxLcf3piaOEmGYm7a6k90F6h30YGBdpOL1cdRNcfRuin136fXTKhTpbH82RVj/b/ww0EJJcYsJiP0mGKCM3ULZ9NkET4x4Z45mAnnORcW+wBZLFdqZdedNYPJjunLqfQZHAOUHvzc8strmxOz3TVWZfy4uMQlOEBeMJJZSoK8ny1GBisdQzeBD9CSn/tiA7lVJWlnEgP3W9TVL8ZQkwRfs+Vdq9M4FvnPuVFrWXa25j1u1Yvk2BRY6g83l7Ffm8NlhkHYkaY09W7tTBNT5m6GNuh8Shb3NNzafa1qpBZuLXev/QSdhkdZ12HcbE820dt1DQqNAkk4iKHXjP6IclLY0QuB6ZwH2scRpABO61r88tgttduTOKbtw5dYqDc5x26+YgMwh8LS2Utgn/V3PgapzkCqKZSK1XA6dl5PiHRBJhdI8nT3Rh40Lr9SS/fra2vv+aUhTzhaVrLHyKLhYSxw73yWF1/NtfFvTA+ZZEWigKj7j0DupxTyKPXKSqkV4tGI2iBd4pPR2bMv/q72EhZiXLd5T7cqvuTj0S8eKXXeaOnduZ74XCzgmpWIZsgkALHpYwKL+TUcIychA0mhDd3652Ov7m0ydCJezISC4hm0J6i2nztWE0AaYQ=
